name: Front-end CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm i

      - name: run cypress tests in chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
          build: npm run build
          start: npm run dev
          wait-on: "http://localhost:5173"
