# name: Run Tests

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/setup-node@v3

#       - name: Use Node.js 20
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20
#           cache: "npm"

#       #   - name: Install dependencies
#       #     run: npm install

#       - name: Run tests
#         run: npm run cy:run-e2e

name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cy:run-e2e
